Repository Strip3s/PhoenixBot, pull requests merged in 2020-11, with the labels that each got.

#2 Data folder fix
  .gitignore
  README.md
  data/profiles.json
  data/proxies.json
Labels: bug

#7 Autogenerate CC Encryption Secret on App Launch
  .gitignore
  README.md
  app.py
  data/vault.json
  images/birdbot.png
  pages/profilespage.py
  pages/proxiespage.py
  pages/settingspage.py
  utils.py
Labels: bug, enhancement

#11 Add default issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#9 Adding 'WaitForConfirmation' Dialog Box
  app.py
  pages/homepage.py
  pages/pollbrowser.py
  sites/walmart.py
Labels: bug

#8 Implemented dont_buy setting and fixed some typos
  data/settings.json
  pages/settingspage.py
  settings.py
  sites/__init__.py
  sites/bestbuy.py
  sites/walmart.py
Labels: enhancement

#14 Data folder cleanup
  README.md
  app.py
  data/profiles.json
  data/proxies.json
  data/tasks.json
  data/vault.json
  requirements.txt
  settings.py
  sites/bestbuy.py
  sites/walmart.py
  utils.py
Labels: breaking change, bug, documentation

#21 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#22 Fixing broken requirements chromedriver-py
  requirements.txt
Labels: bug

#23 Added random delay between .10 and .40 seconds to waiting for restock…
  README.md
  settings.py
  sites/walmart.py
  utils.py
Labels: enhancement

#27 Added random_delay() to Best Buy
  sites/bestbuy.py
  sites/walmart.py
Labels: enhancement

#30 Added Random Delay to GUI Settings page
  data/settings.json
  pages/settingspage.py
  settings.py
  sites/bestbuy.py
  sites/walmart.py
  utils.py
Labels: enhancement

#41 Update walmart.py to ignore SSL errors and correctly open captcha prompts
  sites/walmart.py
Labels: bug

#40 update discord invite link
  README.md
Labels: documentation

#45 new theme for new name and logo
  app.py
  images/cart.png
  images/down_icon.png
  images/downarrow_icon.png
  images/edit.png
  images/home.png
  images/home_alt.png
  images/images.py
  images/play.png
  images/profiles.png
  images/profiles_alt.png
  images/proxies.png
  images/proxies_alt.png
  images/settings.png
  images/settings_alt.png
  images/stop.png
  images/success.png
  images/tasks.png
  images/trash.png
  images/uparrow_icon.png
  pages/createdialog.py
  pages/homepage.py
  pages/pollbrowser.py
  pages/profilespage.py
  pages/proxiespage.py
  pages/settingspage.py
  theming/styleHelper.js
  theming/styles.py
Labels: enhancement

#46 Add the possibility to select Canada as a country
  pages/profilespage.py
Labels: enhancement

#32 Target
  pages/createdialog.py
  pages/homepage.py
  pages/settingspage.py
  settings.py
  sites/target.py
  utils.py
Labels: enhancement

#52 Updating requirements.txt to use hashes; updated lxml to 4.6.1 to resolve XSS vulnerability.
  README.md
  requirements.in
  requirements.txt
Labels: enhancement

#49 GameStop
  pages/createdialog.py
  pages/homepage.py
  pages/settingspage.py
  settings.py
  sites/gamestop.py
Labels: enhancement

#54 GameStop Improvements
  sites/gamestop.py
Labels: enhancement

#57 fix target setting keys and login/payment steps in checkout
  .gitignore
  pages/settingspage.py
  sites/target.py
Labels: bug

#28 Refactor Best Buy Checkout Procedure
  README.md
  app.py
  pages/homepage.py
  pages/settingspage.py
  requirements.in
  requirements.txt
  settings.py
  sites/bestbuy.py
  sites/gamestop.py
  sites/target.py
  sites/walmart.py
  utils.py
  utils/__init__.py
  utils/json_utils.py
  utils/selenium_utils.py
  webhook.py
Labels: enhancement
